all: 
  hosts:
    test_instance:
      ansible_connection: ssh
      ansible_host: 172.18.65.126
      ansible_port: 22
      ansible_user: installer
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: test_instance
      volttron_home: ~/.volttron
    instance1:
      ansible_connection: ssh
      ansible_host: 172.18.65.126
      ansible_port: 22
      ansible_user: installer
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: instance1
      volttron_home: ~/.volt1

    instance2:
      ansible_connection: ssh
      ansible_host: 172.18.65.126
      ansible_port: 22
      ansible_user: installer
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: instance2
      volttron_home: ~/.volt2




